/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_argeo_api_uuid_NativeUuidFactory */

#ifndef _Included_org_argeo_api_uuid_NativeUuidFactory
#define _Included_org_argeo_api_uuid_NativeUuidFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_argeo_api_uuid_NativeUuidFactory
 * Method:    timeUUID
 * Signature: ()Ljava/util/UUID;
 */
JNIEXPORT jobject JNICALL Java_org_argeo_api_uuid_NativeUuidFactory_timeUUID
  (JNIEnv *, jobject);

/*
 * Class:     org_argeo_api_uuid_NativeUuidFactory
 * Method:    nameUUIDv5
 * Signature: (Ljava/util/UUID;[B)Ljava/util/UUID;
 */
JNIEXPORT jobject JNICALL Java_org_argeo_api_uuid_NativeUuidFactory_nameUUIDv5
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     org_argeo_api_uuid_NativeUuidFactory
 * Method:    nameUUIDv3
 * Signature: (Ljava/util/UUID;[B)Ljava/util/UUID;
 */
JNIEXPORT jobject JNICALL Java_org_argeo_api_uuid_NativeUuidFactory_nameUUIDv3
  (JNIEnv *, jobject, jobject, jbyteArray);

/*
 * Class:     org_argeo_api_uuid_NativeUuidFactory
 * Method:    randomUUIDStrong
 * Signature: ()Ljava/util/UUID;
 */
JNIEXPORT jobject JNICALL Java_org_argeo_api_uuid_NativeUuidFactory_randomUUIDStrong
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
